FROM node:18-alpine as build

WORKDIR /app

COPY frontend/ /app/

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
